import { test, expect } from '@playwright/test';

test.describe('Automated UI Interactions', () => {

  test('1. CLICK ALL BUTTONS & 4. TAKE SCREENSHOTS', async ({ page }) => {
    // Navigate to homepage
    await page.goto('/');

    // 4. Screenshots: Full page load
    await page.screenshot({ path: 'test-results/screenshots/home-load.png', fullPage: true });

    // 1. Click all buttons
    const buttons = await page.locator('button, [role="button"]').all();
    console.log(`Found ${buttons.length} buttons on the page.`);

    for (let i = 0; i < buttons.length; i++) {
      const btn = buttons[i];
      const text = await btn.textContent();
      const cleanName = text ? text.replace(/[^a-z0-9]/gi, '-').toLowerCase() : `btn-${i}`;
      
      // Bring into view
      await btn.scrollIntoViewIfNeeded();

      // Screenshot before
      await page.screenshot({ path: `test-results/screenshots/before-${cleanName}-click.png` });

      try {
        await btn.click({ timeout: 2000 });
        console.log(`✅ Success: Clicked button "${text?.trim()}"`);
      } catch (err) {
        console.log(`❌ Failed: Could not click button "${text?.trim()}"`);
      }

      // Screenshot after
      await page.screenshot({ path: `test-results/screenshots/after-${cleanName}-click.png` });
    }
  });

  test('2. CHECK ALL LINKS', async ({ page, request }) => {
    await page.goto('/');
    
    const links = await page.locator('a').all();
    console.log(`Found ${links.length} links on the page.`);

    const brokenLinks: any[] = [];
    
    for (let i = 0; i < links.length; i++) {
        const linkText = await links[i].textContent();
        const textCln = linkText?.trim() || 'unnamed-link';
        const href = await links[i].getAttribute('href');

        if (!href || href === '#' || href.startsWith('javascript:')) {
            console.log(`⚠️ Broken/Empty/Fragment Link: "${textCln}" -> ${href}`);
            brokenLinks.push({ text: textCln, href, status: 'Empty/Invalid' });
            continue;
        }

        try {
            // Resolve relative URLs using the active page URL
            const targetUrl = new URL(href, page.url()).toString();
            const response = await request.get(targetUrl);
            
            if (response.ok()) {
                console.log(`✅ Working Link: "${textCln}" -> ${href}`);
            } else {
                console.log(`❌ Broken Link (Status ${response.status()}): "${textCln}" -> ${href}`);
                brokenLinks.push({ text: textCln, href, status: response.status() });
            }
        } catch (err) {
            console.log(`❌ Error fetching link: "${textCln}" -> ${href}`);
            brokenLinks.push({ text: textCln, href, status: 'Fetch/Parse Error' });
        }
    }

    if (brokenLinks.length > 0) {
        console.log('\n--- BROKEN LINKS REPORT ---');
        console.table(brokenLinks);
    } else {
        console.log('✅ No broken links found!');
    }
  });

  test('3. TEST FORMS & INPUTS', async ({ page }) => {
    await page.goto('/');

    // Discover standard text inputs and fill them
    const textInputs = await page.locator('input[type="text"]').all();
    for (const input of textInputs) {
      if (await input.isVisible()) await input.fill('Demo Subject');
    }
    
    // Discover emails
    const emailInputs = await page.locator('input[type="email"]').all();
    for (const email of emailInputs) {
      if (await email.isVisible()) await email.fill('test@playwright.dev');
    }

    // Discover textareas
    const textareas = await page.locator('textarea').all();
    for (const ta of textareas) {
      if (await ta.isVisible()) await ta.fill('This is a robotic transmission sequence generated by Playwright ensuring forms work correctly.');
    }

    // Screenshot state after filling forms out
    await page.screenshot({ path: 'test-results/screenshots/form-filled-before-submit.png', fullPage: true });

    // Look specifically for Transmit/Submit buttons near the form
    const submitBtn = page.locator('button', { hasText: /(submit|send|transmit)/i }).first();
    
    if (await submitBtn.isVisible()) {
        await submitBtn.scrollIntoViewIfNeeded();
        
        try {
            await submitBtn.click({ timeout: 2000 });
            console.log('✅ Success: Form submission button clicked.');
        } catch(e) {
            console.log('❌ Failed: Could not click the form submit button.');
        }
    } else {
        console.log('⚠️ Could not find a specific submit button (maybe custom styling?). Fallback check ignored.');
    }

    // Screenshot after form submission
    await page.screenshot({ path: 'test-results/screenshots/form-after-submit.png' });
  });
});
